# Maven
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription â€“ MPN(1)(4ef05457-99d1-4ef6-9326-8579fa756fcc)'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:workspace66736.sql.azuresynapse.net,1433;Initial Catalog=test;Persist Security Info=False;User ID=sqladminuser;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'InlineSqlTask'
    SqlInline: 'CREATE DATABASE coone;'
    IpDetectionMethod: 'AutoDetect'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#trigger:
#- main

#pool:
#  vmImage: ubuntu-latest

#steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'


pool:  
  name: local 

trigger: none 

steps: 
- script: echo Hello, world! 
  displayName: 'Run a one-line script' 